# Generated by Django 4.2 on 2023-04-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendclassmaster',
            name='data',
            field=models.DateField(editable=False),
        ),
    ]
