# Generated by Django 3.2 on 2023-04-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0006_auto_20230425_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fields',
        ),
    ]
