# Generated by Django 3.2 on 2023-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0008_selectfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceentry',
            name='pafield',
            field=models.IntegerField(max_length=1),
        ),
    ]
