# Generated by Django 3.2 on 2023-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teachersregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tclass', models.IntegerField(blank=True)),
                ('tsession', models.CharField(max_length=10)),
                ('tdate', models.DateTimeField(auto_now_add=True)),
                ('ttatus', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
