# Generated by Django 3.2 on 2023-04-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersregister',
            old_name='ttatus',
            new_name='tstatus',
        ),
    ]
