# Generated by Django 3.2 on 2023-04-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_ttatus_teachersregister_tstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachersregister',
            old_name='tstatus',
            new_name='status',
        ),
    ]
