# Generated by Django 3.2 on 2023-04-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20230421_0711'),
        ('teachers', '0003_rename_tstatus_teachersregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersregister',
            name='tclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classesregister'),
        ),
    ]
