# Generated by Django 3.2 on 2023-04-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classesregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cclass', models.IntegerField(blank=True)),
                ('csession', models.CharField(max_length=10)),
                ('tdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, default=1)),
            ],
        ),
    ]
