# Generated by Django 3.2 on 2023-04-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classesregister',
            old_name='tdate',
            new_name='cdate',
        ),
    ]
