# Generated by Django 3.2 on 2023-04-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_tdate_classesregister_cdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesregister',
            name='cclass',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
