# Generated by Django 4.2 on 2023-04-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20230421_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classesregister',
            name='cclass',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
