# Generated by Django 3.2 on 2023-04-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classesregister_cclass'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsregister',
            name='sclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classesregister'),
        ),
    ]
