# Generated by Django 3.2 on 2023-04-21 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_studentsregister_sclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsregister',
            old_name='sclass',
            new_name='cclass',
        ),
    ]
