# Generated by Django 3.2 on 2023-04-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_sclass_studentsregister_cclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsregister',
            old_name='cclass',
            new_name='sclass',
        ),
    ]
